### ISSUE TITLE
Could you add the "Happy" endpoint

### ISSUE THREAD

**Issue by countchrisdo** [weeebdev/waifu.pics#8]
Love this API wrapper, thank you so much for making it. I'd love to be able to use [https://waifu.now.sh/sfw/happy](https://waifu.now.sh/sfw/happy) with it. Thanks

**Comment by weeebdev** [comment]
I'm sorry that I couldn't afford your request in time. For some reason, I didn't get a notification about this issue

**Comment by countchrisdo** [comment]
It's no problem, it's awesome you actually added it!
